apiVersion: v1
kind: Service
metadata:
  name: dashboard-hystrix
  labels:
    app: dashboard-hystrix 
spec:
  type: LoadBalancer
  ports:
  - name: dashboard-hystrix
    port: 80 
    targetPort: 7979
  selector:
    app: dashboard-hystrix 
