apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dashboard-hystrix
  labels:
    app: dashboard-hystrix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard-hystrix
  template:
    metadata:
      labels:
        app: dashboard-hystrix
    spec:
      containers:
      - name: dashboard-hystrix
        image: docker.io/pipelineai/dashboard-hystrix:1.5.0
        imagePullPolicy: "Always"
        env:
        - name: GET_HOSTS_FROM
          value: env
        ports:
        - containerPort: 7979
