apiVersion: v1
kind: Service
metadata:
  name: dashboard-turbine
  labels:
    app: dashboard-turbine
spec:
  type: LoadBalancer
  ports:
  - name: http 
    port: 8989 
    targetPort: 8989
  - name: jmx 
    port: 8990 
    targetPort: 8990
  selector:
    app: dashboard-turbine
