apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dashboard-turbine
  labels:
    app: dashboard-turbine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard-turbine
  template:
    metadata:
      labels:
        app: dashboard-turbine
    spec:
      containers:
      - name: dashboard-turbine
        image: docker.io/pipelineai/dashboard-turbine:master
        imagePullPolicy: "Always"
        env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        ports:
        - containerPort: 8989
        - containerPort: 8990
